package com.group1.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CheckPlanDesign extends VerticalLayout {
	protected TextField planNameTf;
	protected TextField projectIdTf;
	protected TextArea planPurposeTa;
	protected TextArea planPlaceTa;
	protected TextArea planPartnerTa;
	protected CheckBox planAdvanceChbox;
	protected CheckBox planArisedChBox;
	protected TextField empNameTf;
	protected TextField empEmailTf;
	protected TextField empChucVuTf;
	protected VerticalLayout jobListLayout;
	protected Button cancelBtn;
	protected Button checkBtn;
	protected Button unCheckBtn;

	public CheckPlanDesign() {
		Design.read(this);
	}
}
