package com.group1.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EmployeeDesign extends VerticalLayout {
	protected TextField empIdTf;
	protected TextField nameTf;
	protected TextField emailTf;
	protected TextField addressTf;
	protected TextField phoneTf;
	protected TextField chucvuIdTf;
	protected Button chucvuInfoBtn;
	protected TextField groupIdTf;
	protected Button groupInfoBtn;
	protected Button cancelBtn;
	protected Button editBtn;
	protected Button removeBtn;
	protected Button okBtn;

	public EmployeeDesign() {
		Design.read(this);
	}
}
