package com.group1.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends HorizontalLayout {
	protected Button menuButton;
	protected CssLayout menu;
	protected Button proposeBtn;
	protected Button checkBtn;
	protected Button reportBtn;
	protected Button adminBtn;
	protected Button userBtn;
	protected Button logoutBtn;
	protected Label empNameLbl;
	protected CssLayout contentLayout;

	public MainDesign() {
		Design.read(this);
	}
}
