package com.group1.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PlanDesign extends VerticalLayout {
	protected VerticalLayout planInfoLayout;
	protected TextField planNameTf;
	protected TextField projectIdTf;
	protected TextArea planPurposeTf;
	protected TextArea planPlaceTf;
	protected TextArea planPartnerTf;
	protected CheckBox planAdvanceChbo;
	protected CheckBox planArisedChbox;
	protected VerticalLayout jobListLayout;
	protected Button addJobBtn;
	protected HorizontalLayout planButtonLayout;
	protected Button cancelBtn;
	protected Button proposeBtn;
	protected Button editBtn;
	protected Button deleteBtn;
	protected Button proposePaymentBtn;
	protected HorizontalLayout checkButtonLayout;
	protected Button checkCancelBtn;
	protected Button checkBtn;
	protected Button unCheckBtn;
	protected Button reportBtn;

	public PlanDesign() {
		Design.read(this);
	}
}
