package com.group1.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserDesign extends VerticalLayout {
	protected TextField userIdTf;
	protected TextField empIdTf;
	protected Button viewEmpBtn;
	protected TextField usernameTf;
	protected TextField passTf;
	protected CheckBoxGroup<java.lang.String> roleChboxGroup;
	protected Button cancelBtn;
	protected Button editBtn;
	protected Button removeBtn;
	protected Button okBtn;

	public UserDesign() {
		Design.read(this);
	}
}
